title: Project
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: category
            field:
              mode: default
              type: taxonomies
              display: Category
              icon: taxonomy
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: featured_image
            field:
              max_files: 1
              min_files: 1
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: 'Featured Image'
              icon: assets
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: content
            field:
              type: markdown
              display: Content
              localizable: true
          -
            handle: tags
            field:
              type: list
              display: Tags
              icon: list
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: github_link
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Github Link'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: demo_site
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Demo Site'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
          -
            handle: type
            field:
              type: terms
              taxonomies:
                - type
              display: Type
              mode: select
