title: Project
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: category
            field:
              mode: default
              type: taxonomies
              display: Category
              icon: taxonomy
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: featured_image
            field:
              max_files: 1
              min_files: 1
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: 'Featured Image'
              icon: assets
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: summary
            field:
              type: markdown
              display: Summary
              localizable: true
              instructions_position: above
              listable: hidden
              visibility: visible
              replicator_preview: true
              restrict: false
              buttons:
                - bold
                - italic
                - unorderedlist
                - orderedlist
                - quote
                - link
                - image
                - table
              automatic_line_breaks: true
              automatic_links: false
              escape_markup: false
              heading_anchors: false
              smartypants: false
              table_of_contents: false
              antlers: false
              hide_display: false
          -
            handle: post_body
            field:
              buttons:
                - h2
                - h3
                - bold
                - italic
                - unorderedlist
                - orderedlist
                - removeformat
                - quote
                - anchor
                - image
                - table
              smart_typography: false
              save_html: true
              inline: false
              toolbar_mode: fixed
              reading_time: false
              word_count: false
              fullscreen: true
              allow_source: true
              enable_input_rules: true
              enable_paste_rules: true
              remove_empty_nodes: false
              antlers: false
              link_noopener: false
              link_noreferrer: false
              target_blank: false
              always_show_set_button: false
              collapse: false
              previews: true
              type: bard
              display: 'Post Body'
              icon: bard
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              sets:
                blocks:
                  display: Blocks
                  instructions: null
                  icon: null
                  sets:
                    video_block:
                      display: 'Video Block'
                      instructions: null
                      icon: null
                      fields:
                        -
                          handle: iphone_video_field
                          field:
                            type: video
                            display: 'iPhone Video Field'
                            icon: video
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            replicator_preview: true
                            hide_display: false
                    desktop_video_block:
                      display: 'Desktop Video Block'
                      instructions: null
                      icon: null
                      fields:
                        -
                          handle: video_url
                          field:
                            type: video
                            display: 'Video URL'
                            icon: video
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            replicator_preview: true
                            hide_display: false
                    single_image:
                      display: 'Single Image'
                      instructions: null
                      icon: null
                      fields:
                        -
                          handle: image_url
                          field:
                            max_files: 1
                            min_files: 1
                            mode: list
                            container: assets
                            restrict: false
                            allow_uploads: true
                            show_filename: true
                            show_set_alt: true
                            type: assets
                            display: 'Image Url'
                            icon: assets
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            replicator_preview: true
                            hide_display: false
          -
            handle: tags
            field:
              type: list
              display: Tags
              icon: list
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: github_link
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Github Link'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: demo_site
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Demo Site'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
          -
            handle: type
            field:
              type: terms
              taxonomies:
                - type
              display: Type
              mode: select
